### ISSUE TITLE
Publish on elm packages

### ISSUE THREAD

**Issue by nsb** [mvader/elm-localstorage#2]
Would be great if you would publish this on elm packages.

**Comment by mvader** [comment]
Last time I checked they were not accepting native modules and the review
process was stopped. Has it started again?

**Comment by nsb** [comment]
Ok, I didn't know that. Thanks.

man. 3. okt. 2016 kl. 14.20 skrev Miguel Molina <notifications@github.com>:

**Comment by roSievers** [comment]
I am also looking for a package to access local storage and thought about using this package. I was listening to the [Elm Town episode on JS interop](https://elmtown.github.io/2016/11/07/js-in-elm-town-episode-4.html) today and thought about your API again.

I am certain your current API is not going to get published, even if the native review process is restarted. The root problem is, that local storage creates another "island of state" outside of Elm. A a consequence `get : String -> Maybe String` is **not** a function. That is because it isn't [well defined](https://en.wikipedia.org/wiki/Well-defined), call `get "myProperty"` twice and you might get different results.

Breaking the core guarantee that functions are, well, functions in a mathematical sense has the potential to break programs in weird ways. (The compiler might shuffle around the order, do optimisations that change the behaviour of your code, ...)

The resulting code can definitely be used to get things done (they also mention this in the Elm Town podcast) but not something Evan would want on elm-package.

**Comment by mvader** [comment]
Yep, I actually doubt as well that it would be accepted because of the things you mentioned. This library is basically to "get things done".

To do things right what you probably want is https://github.com/elm-lang/persistent-cache (which is an official library).
